# -*- coding: utf-8 -*-
"""API News.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wWPy-lFnu8lVJvury-AUH7_CjT6W-Bsc
"""

import numpy as np
import pandas as pd
import requests

url_news = 'http://newsapi.org/v2/everything?'
queries = {
    'q' : 'tesla',
    'from' : '2021-01-31',
    'sortBy' : 'publishedAt',
    'apiKey' : 'ab18a652e5854e8db4932ebc1ca7842d'
}

response = requests.get(url_news, params=queries)

response.status_code

news = response.json()

news

Company_name = 'Tesla'

temp = []
for obj in news['articles']:
    author = obj['author'],
    content = obj['content']
    description = obj['description']
    time = obj['publishedAt']
    source = obj['source']
    title = obj['title']
    row = [Company_name, author, content, description, time, source, title]
    temp.append(row)
DataFrame_News = pd.DataFrame(temp, columns=['Company Name','Author','Content','Description','Time','Source','Title'])
DataFrame_News