# -*- coding: utf-8 -*-
"""Salinan dari Basic Dataframe (Pandas).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PSR0i6nafXeq0F9X7SEjrcYY4pVKcbu2

# Load Library
"""

import pandas as pd
import numpy as np

"""# Creating DataFrame

## Create from List
"""

A = [1,2,3,4,5,6]
B = [2,3,4,5,6,7]
df = pd.DataFrame(list(zip(A, B)), columns=['A', 'B'])
df

"""## Create from Array"""

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(array, columns=['A', 'B', 'C'])
df

"""## Create from Series"""

A = pd.Series([1,2,3,4,5,6])
B = pd.Series([2,3,4,5,6,7])
df = pd.DataFrame(A, columns=['A'])
df['B'] = B
df

"""## Create from Tuple"""

tuple1 = tuple([1,2,3,4,5])
tuple2 = tuple([6,7,8,9,10])
df = pd.DataFrame([tuple1, tuple2])
df

"""## Create from Dictionary"""

author = ['Jack', 'John', 'Sam', 'Mike'] 
article = [210, 211, 114, 178] 
dictionary = { 'Author': author, 'Article': article }
df = pd.DataFrame(dictionary)
df

"""## Create from Looping List"""

c = [3, 4, 5, 4, 8, 6]
d = [1, 2, 3, 4, 5, 6]
e = [10, 11, 12, 13, 14, 16]
column_names = ['One', 'Two', 'Three']
group = [c, d, e]
for col in range(len(group)):
    if col == 0:
        data = pd.DataFrame(group[col], columns=[column_names[col]])
    else:
        data[column_names[col]] = group[col]
data

"""# Selecting Dataframe

## Show top/bottom dataframe
"""

# Top 5
df.head(5)

# Bottom 5
df.tail(5)

"""## Get the dimension of dataframe"""

# Shape of Dataframe
print(df.shape)

# Size of Dataframe
print(df.size)

# Total rows of Dataframe
print(len(df))
print(df.shape[0])

"""## Get Data type and descriptive statistics"""

# Get data types
df.dtypes

# Get descriptive statistics
df.describe()

"""## Get column names"""

# Column Names
df.columns

"""## Selecting specific rows"""

sample = df[1:8]
sample = df.iloc[1:8]

"""## Selecting specific columns"""

sample = df['first']
sample = df[['first', 'second']]
sample = df.loc[:, ['first', 'second']]

"""## Selecting from rows and columns"""

# From its index
selected_df = df.iloc[0:1000, [1,3,4]]
selected_df = df.iloc[[1,2,3,4,100,200], 0:3]

# From its name
selected_df = df.loc[0:100, ['first', 'second']]

"""## Sampling the dataframe"""

sample = df.sample(n=None, frac=None, random_state=None)