# -*- coding: utf-8 -*-
"""Feature Engineering and Imbalanced.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dn_3o77rIp0cQeEfQiobquH61Sv2LaPt

# Import Libraries
"""

import pandas as pd, numpy as np
from google.colab import drive
# Mount Google Drive
drive.mount('/content/gdrive')

"""# Load Dataset"""

df = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Dataset Latihan/keywords.csv')
df.head()

"""# Feature Engineering"""

# New Feature
df['CTR'] = df['Clicks'] / df['Impressions']
df['CPI'] = df['Cost'] / df['Impressions']
df['CPC'] = df['Cost'] / df['Clicks']

# Fill Missing Value
df.fillna(value=0, inplace=True)
df.head()

# Descriptive Statistics
df.describe()

# Change Infinite Value into 0
df = df.replace([np.inf, -np.inf], 0)

"""# Merge with Data Statistical Value"""

# Validate how many categories inside feature
df.Market.unique()

market_data = df.pivot_table(index='Market', values=['Clicks', 'Impressions', 'Cost', 'CPI', 'CPC', 'CTR']
                                  , aggfunc=[np.mean, np.median, np.max])

# Information per calculation
mean_market = market_data['mean'].reset_index()
med_market = market_data['median'].reset_index()
max_market = market_data['amax'].reset_index()

# change column names
mean_market.columns = ['Market', 'mean_market_CPC', 'mean_market_CPI', 'mean_market_CTR', 'mean_market_Clicks', 'mean_market_Cost', 'mean_market_Impressions']
med_market.columns = ['Market', 'med_market_CPC', 'med_market_CPI', 'med_market_CTR', 'med_market_Clicks', 'med_market_Cost', 'med_market_Impressions']
max_market.columns = ['Market', 'max_market_CPC', 'max_market_CPI', 'max_market_CTR', 'max_market_Clicks', 'max_market_Cost', 'max_market_Impressions']

# Join those dataset
market_data = pd.merge(mean_market, med_market, how='inner', on='Market')
market_data = pd.merge(market_data, max_market, how='inner', on='Market')
market_data

del mean_market, med_market, max_market

# Join created market data with df
df = pd.merge(df, market_data, how='left', on='Market')
df.head()

"""# Imbalanced Data"""

from imblearn.over_sampling import SMOTE

# Label the target
df.loc[df['CTR'] < 0.02, 'labels'] = 0
df.loc[df['CTR'] >= 0.02, 'labels'] = 1
df['labels'].value_counts()

df = df.drop(['Date', 'Market', 'Keyword'], axis=1)

X = dataset.drop(['labels'], 1)
y = dataset['labels']

oversample = SMOTE()
X, y = oversample.fit_resample(X, y)

pd.Series(y).value_counts()