# -*- coding: utf-8 -*-
"""Salinan dari Session 20 - Advanced Dataframe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jQVcclci-tRVIsB18GIvqoZLAU00h67c

# Import Libraries
"""

import pandas as pd, numpy as np
from google.colab import drive
drive.mount('/content/gdrive')

"""# Load datasets"""

path_1 = '/content/gdrive/MyDrive/Colab Notebooks/Dataset Latihan/order_details.csv'
path_2 = '/content/gdrive/MyDrive/Colab Notebooks/Dataset Latihan/order_lists.csv'

details = pd.read_csv(path_1)
lists = pd.read_csv(path_2)

"""# Show Datasets"""

details.head()

lists.head()

"""# Join Table

## Merge method
"""

pd.merge(details, lists, how='right', on='order_id').shape

"""## Join Method"""

details.join(lists.set_index('order_id'), how='left', on='order_id').shape

"""## Cross Join

"""

# Define a dictionary of user ID 
dict1 = {'Name': ["Jack", "John", "Mike"], 
        'UserID': [1, 2, 3]}  
     
# Define a dictionary of product ID  
dict2 = {'ProductID': ['pdct1', 'pdct2', 'pdct3', 'pdct4']}  
   
# Convert the dictionary to DataFrame   
df = pd.DataFrame(dict1)
df1 = pd.DataFrame(dict2)
  
# Perform cross join, use key column in the DataFrames 
df['key'] = 1
df1['key'] = 1
  
# Print Result. 
result = pd.merge(df, df1, on ='key').drop("key", 1)

result

"""# Concatenate Dataframe"""

pd.concat([details, lists], axis=0)

"""# Append Dataframe"""

details.append(lists)

"""# Melting Table"""

d1 = {"Name": ["Nick", "John", "Leo"],
      "ID": [1, 2, 3],
      "Role": ["CEO", "Assistant", "Manager"]}
df = pd.DataFrame(d1)
df

df_melted = pd.melt(df, id_vars=["ID"], value_vars=["Name", "Role"])
df_melted

"""# Lambda functions"""

x = lambda a : a + 100
print(x(10))